include catppuccin_macchiato.conf

background_opacity 0.84
map ctrl+alt+enter new_window_with_cwd
enable_audio_bell no

scrollback_lines 900000

shell /usr/bin/nu

font_size 9


inactive_text_alpha 0.8
hide_window_decorations yes

allow_remote_control yes

map ctrl+b combine | fourth_window | send_text all \x03 | sleep 0.2s | send_text all \fjust build \r | nth_window -1
map ctrl+t combine | fourth_window | send_text all \x03 | sleep 0.2s | send_text all \fjust test \r | nth_window -1
map ctrl+r combine | third_window | send_text all \x03 | sleep 0.2s | send_text all \fjust run \r | nth_window -1
